query homeQuery {
  ...LayoutQueryFragment
  page(relativePath: "home.mdx") {
    ...PageParts
  }
  postConnection(sort: "date", last: 6, filter: { published: { eq: true } }) {
    edges {
      node {
        _sys {
          filename
        }
        ...PostParts
      }
    }
  }
}

query paginationQuery($limit: Float, $before: String) {
  ...LayoutQueryFragment
  postConnection(
    sort: "date"
    last: $limit
    before: $before
    filter: { published: { eq: true } }
  ) {
    edges {
      cursor
      node {
        ...PostParts
        _sys {
          filename
        }
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}

query pageQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    _sys {
      filename
    }
    ...PostParts
  }
}

query tagPageQuery($tag: [String]) {
  ...LayoutQueryFragment
  postConnection(
    sort: "date"
    filter: { published: { eq: true }, tags: { in: $tag } }
  ) {
    edges {
      cursor
      node {
        _sys {
          filename
        }
        ...PostParts
      }
    }
  }
}

query searchQuery {
  ...LayoutQueryFragment
  postConnection {
    edges {
      node {
        _sys {
          filename
        }
        ...PostParts
      }
    }
  }
}

query layoutQuery {
  ...LayoutQueryFragment
}
